services:
  frontend:
    build:
      context: frontend
    container_name: frontend
    environment:
      # BACKEND_URL: 'http://localhost:8000/api'
      BACKEND_URL: 'http://localhost:8000/api'
    ports:
      - '8080:80'
    depends_on:
      - backend

  backend:
    build:
      context: backend
    container_name: backend
    ports:
      - '8000:8000'
    command: [ 'sh', '-c', 'npm run seed && npm run start' ]
    depends_on:
      - mongo
    environment:
      MONGO_URI: 'mongodb://mongo:27017/mern-shop'
      # Frontend URL for CORS
      ORIGIN: 'http://localhost:8080'
      EMAIL: 'demo@gmail.com'
      PASSWORD: 'helloWorld@123'
      LOGIN_TOKEN_EXPIRATION: '30d'
      OTP_EXPIRATION_TIME: '120000'
      PASSWORD_RESET_TOKEN_EXPIRATION: '2m'
      COOKIE_EXPIRATION_DAYS: '30'
      SECRET_KEY: 'supersecret'
      PRODUCTION: 'false'

  mongo:
    image: mongo:latest
    container_name: mongodb
    command: mongod #--quiet --logpath /dev/null
    ports:
      - '27017:27017'
