apiVersion: v1
kind: Service
metadata:
  name: {{ include "mern-shop.fullname" . }}-backend
  labels:
    io.kompose.service: backend
  {{- include "mern-shop.labels" . | nindent 4 }}
  annotations:
    kompose.cmd: kompose convert -o kompose/
    kompose.version: 1.34.0 (cbf2835db)
    alb.ingress.kubernetes.io/healthcheck-path: '/api/healthz'
spec:
  type: {{ .Values.backend.type }}
  selector:
    io.kompose.service: backend
  {{- include "mern-shop.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.backend.ports | toYaml | nindent 2 }}
