apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mern-shop.fullname" . }}-backend-config
  labels:
  {{- include "mern-shop.labels" . | nindent 4 }}
data:
  COOKIE_EXPIRATION_DAYS: {{ .Values.backendConfig.cookieExpirationDays | quote }}
  EMAIL: {{ .Values.backendConfig.email | quote }}
  LOGIN_TOKEN_EXPIRATION: {{ .Values.backendConfig.loginTokenExpiration | quote }}
  ORIGIN: {{ .Values.backendConfig.origin | quote }}
  OTP_EXPIRATION_TIME: {{ .Values.backendConfig.otpExpirationTime | quote }}
  PRODUCTION: {{ .Values.backendConfig.production | quote }}
