apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mern-shop.fullname" . }}-backend-secrets
  labels:
  {{- include "mern-shop.labels" . | nindent 4 }}
data:
  MONGO_URI: {{ required "backendSecrets.mongoUri is required" .Values.backendSecrets.mongoUri
    | b64enc | quote }}
  PASSWORD: {{ required "backendSecrets.password is required" .Values.backendSecrets.password
    | b64enc | quote }}
  SECRET_KEY: {{ required "backendSecrets.secretKey is required" .Values.backendSecrets.secretKey
    | b64enc | quote }}
type: Opaque
