apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mern-shop.fullname" . }}-frontend-config
  labels:
  {{- include "mern-shop.labels" . | nindent 4 }}
data:
  BACKEND_URL: {{ .Values.frontendConfig.backendUrl }}
