apiVersion: v1
kind: Service
metadata:
  name: {{ include "mern-shop.fullname" . }}-frontend
  labels:
    io.kompose.service: frontend
  {{- include "mern-shop.labels" . | nindent 4 }}
  annotations:
    kompose.cmd: kompose convert -o kompose/
    kompose.version: 1.34.0 (cbf2835db)
spec:
  type: {{ .Values.frontend.type }}
  selector:
    io.kompose.service: frontend
  {{- include "mern-shop.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.frontend.ports | toYaml | nindent 2 }}