name: Continous Integration

on:
  pull_request:
    branches:
      - feat/ci
    types: [closed]

jobs:
  setup:
    name: Setup and Configure AWS
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Set environment variables based on branch
        uses: kanga333/variable-mapper@master
        id: export-vars
        with:
          key: "${{ github.ref_name }}"
          export_to: env
          map: |
            {
              "main": {
                "AWS_ACCOUNT_ID": "${{ vars.PROD_AWS_ACCOUNT_ID }}",
                "AWS_REGION": "${{ vars.PROD_AWS_REGION }}",
                "ECR_URL": "${{ vars.PROD_ECR_URL }}",
                "GHA_ROLE_ARN": "${{ vars.PROD_GHA_ROLE_ARN }}",
                "REACT_APP_BASE_URL": "${{ vars.PROD_REACT_APP_BASE_URL }}"
              },
              ".*": {
                "AWS_ACCOUNT_ID": "${{ vars.DEV_AWS_ACCOUNT_ID }}",
                "AWS_REGION": "${{ vars.DEV_AWS_REGION }}",
                "ECR_URL": "${{ vars.DEV_ECR_URL }}",
                "GHA_ROLE_ARN": "${{ vars.DEV_GHA_ROLE_ARN }}",
                "REACT_APP_BASE_URL": "${{ vars.DEV_REACT_APP_BASE_URL }}"
              }
            }

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ env.GHA_ROLE_ARN }}

      - name: Login to ECR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.ECR_URL }}
      
      - name: Create semver tag based on PR labels
        id: semver
        uses: K-Phoen/semver-release-action@master
        with:
          release_branch: ${{ github.ref_name }}
          release_strategy: none
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  frontend-build:
    name: Build Frontend
    runs-on: ubuntu-latest
    needs: setup
    if: ${{ github.event.pull_request.merged == true }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push frontend
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          push: true
          tags: |
            ${{ env.ECR_URL }}/mern-shop/frontend:${{ steps.semver.outputs.tag }}
            ${{ env.ECR_URL }}/mern-shop/frontend:latest
          build-args: |
            REACT_APP_BASE_URL=${{ env.REACT_APP_BASE_URL }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  backend-build:
    name: Build Backend
    runs-on: ubuntu-latest
    needs: setup
    if: ${{ github.event.pull_request.merged == true }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push backend
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          push: true
          tags: |
            ${{ env.ECR_URL }}/mern-shop/backend:${{ steps.semver.outputs.tag }}
            ${{ env.ECR_URL }}/mern-shop/backend:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
