name: Create terraform plan

on:
  - pull_request

jobs:
  plan:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    name: Create a plan for an example terraform configuration
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.DEV_AWS_REGION }}
          role-to-assume: ${{ vars.DEV_GHA_ROLE_ARN }}

      - name: terraform plan
        uses: dflook/terraform-plan@v1
        with:
          path: terraform/dev