name: Terrafrom Apply in prod

on:
  push:
    branches:
      - main
    paths:
      - 'terraform/prod/**'

jobs:
  apply:
    name: Apply approved plan
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      pull-requests: write
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Expose git commit data
        uses: rlespinasse/git-commit-data-action@v1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.PROD_AWS_REGION }}
          role-to-assume: ${{ vars.PROD_GHA_ROLE_ARN }}

      - name: terraform apply
        uses: dflook/terraform-apply@v1
        with:
          auto_approve: ${{ env.GIT_COMMIT_COMMITTER_NAME == 'github-actions[bot]' }}
          path: terraform/prod
          var_file: terraform/prod/terraform.tfvars
          backend_config_file: terraform/prod/backend.tfvars
        env:
          TERRAFORM_PRE_RUN: |
            chmod +x tf-pre-run.sh
            ./tf-pre-run.sh
