name: Terrafrom Apply in dev

on:
  push:
    branches:
      - feat/ci
    paths:
      - 'terraform/dev/**'

jobs:
  apply:
    name: Apply approved plan
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.DEV_AWS_REGION }}
          role-to-assume: ${{ vars.DEV_GHA_ROLE_ARN }}

      - name: terraform apply
        uses: dflook/terraform-apply@v1
        with:
          path: terraform/dev
