name: Terrafrom Apply in dev

on:
  push:
    branches:
      - feat/ci
    paths:
      - 'terraform/dev/**'

jobs:
  apply:
    name: Apply approved plan
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.DEV_AWS_REGION }}
          role-to-assume: ${{ vars.DEV_GHA_ROLE_ARN }}

      - name: terraform apply
        uses: dflook/terraform-apply@v1
        with:
          path: terraform/dev
        env:
          TERRAFORM_PRE_RUN: |
            echo "Installing kubectl"
            STABLE=$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)
            curl -LO "https://dl.k8s.io/release/${STABLE}/bin/linux/amd64/kubectl"
            install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
            kubectl version --client
            echo "Installing helm"
            curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
            chmod 700 get_helm.sh
            ./get_helm.sh
            helm version
    